### ISSUE TITLE
PyCharm

### ISSUE THREAD

**Issue by goodcoder1234** [panzarino/mlbgame#111]
I'm trying to get mlbgame to work with PyCharm, however it won't recognize mlbgame. I've installed pip but still it won't work. Anyone have any suggestions?

**Comment by panzarino** [comment]
@goodcoder1234 I actually developed some of this library with PyCharm, so I know the issue is not with PyCharm. Are you sure that you installed correctly with pip? You say that you installed pip, but have you actually installed mlbgame by running `pip install mlbgame`? In addition, you might be having an issue similar to #96.

**Comment by goodcoder1234** [comment]
<img width="526" alt="screen shot 2018-09-20 at 8 46 14 pm" src="https://user-images.githubusercontent.com/43457529/45859277-4804bb80-bd16-11e8-8d6f-f8936ee117f3.png">

made sure to delete anything named mlbgame too and still not working. Any other suggestions?

**Comment by panzarino** [comment]
@goodcoder1234 You need to type that into a terminal window, not the python file itself.
