### ISSUE TITLE
Caching in data.py

### ISSUE THREAD

**Issue by rwolst** [panzarino/mlbgame#117]
When it comes to loading data, it could be very useful to cache it locally for fast lookup later. It says here (https://github.com/panzarino/mlbgame/blob/master/mlbgame/data.py#L3) that data is cached, however I cannot see any caching actually occurring. Is this something to be added?

One thing to be aware of is that it is unlikely someone would want to use caching during an in play match as in this case repeated requests would likely contain new information.

**Comment by panzarino** [comment]
@rwolst It used to cache data but that functionality was removed as it became too difficult to maintain as the library expanded. Plus, the caching was complicated for the end user to understand and most people did not use it.

**Comment by reddigari** [comment]
Would you be interested in a contribution that allowed a user to specify a path to cached XML files, and then loaded data from file whenever possible? There is a similar library [in this repo](https://github.com/benjamincrom/baseball) that has a data dump for 2008-2017. Doesn't have every endpoint used here, but it has the big ones.

This approach would prevent you from having to maintain caching code, but would allow anyone inclined to download the XML themselves to load from disk instead of over the network every time.

**Comment by panzarino** [comment]
@reddigari I would be interested in that, as long as the user handles caching the correct files. In the past it became too difficult to manage the CLI that cached files.
