### ISSUE TITLE
Q: Current Team Roster

### ISSUE THREAD

**Issue by jethrolam** [panzarino/mlbgame#27]
I am wondering how to retrieve the current roster for each team?  This information is not related to any stat or game, and I also can't find such information from mlbgame.teams().

I believe I can estimate the current roster by looking at the player_stats() of the most recent played game.  But again, that will be an estimate.

Thank you for creating this wonderful API.

**Comment by panzarino** [comment]
I'm not sure if there is a way to get this information, but I will look around to see if mlb has the data somewherr

**Comment by digitalSaint** [comment]
Looks like `players.xml` in the game directory contains the coaching staff, bullpen catchers, 25-man roster plus anyone on the DL.

Here's an example: http://gd2.mlb.com/components/game/mlb/year_2017/month_04/day_15/gid_2017_04_15_houmlb_oakmlb_1/players.xml

http://mlb.mlb.com/mlb/fantasy/injuries/#team117
http://mlb.mlb.com/mlb/fantasy/injuries/#team133

I haven't found a simple way to get the 40-man roster yet.

**Comment by panzarino** [comment]
That's on a per game basis, but I guess mlb.com must just use the data from the most recent game, so they keep creating a new xml file for each game rather than update a centralized one (I assume). That makes it a lot harder to consistently be able to get the most up to date roster, as the only way to get it would be that 25-man roster from the most recent game. 

Not sure how I should go about implementing this feature, any thoughts? Looks like the only way to do it now is on a per game basis, where the user could get the player information by passing a game id as a parameter.

**Comment by digitalSaint** [comment]
@panzarino Have a look at this: https://github.com/wellsoliver/py-mlb/blob/master/py_mlb/fetcher.py#L18

http://mlb.mlb.com/lookup/json/named.roster_40.bam?team_id=117

**Comment by panzarino** [comment]
@digitalSaint very interesting... I will definitely work on implementing that relatively soon.

**Comment by panzarino** [comment]
Closing since this has been implemented into `master`.
