### ISSUE TITLE
Player stats output for example does not match the expected output.

### ISSUE THREAD

**Issue by johnsbr1** [panzarino/mlbgame#72]
Player names and positions are still returned, but I am unable to access the batting statistics.

![image](https://user-images.githubusercontent.com/28379006/37742734-c6116ce8-2d34-11e8-9da8-d78bcfc2136a.png)

**Comment by trevor-viljoen** [comment]
That's because you're only printing the player object which returns a formatted string with player name and position: https://github.com/panzarino/mlbgame/blob/master/mlbgame/stats.py#L269

This prints out key, value pairs for each player. 
```
for player in stats.home_batting:
     for key in player.__dict__.keys():
         print('{0} => {1}'.format(key, player.__dict__[key]))
```

To access specific `player_stats` attributes: 
```
for player in stats.home_batting:
    print(player.name_display_first_last)
```

For a list of those attributes, look at the output of the first loop I gave you or look here: https://github.com/panzarino/mlbgame/blob/master/mlbgame/stats.py#L198

**Comment by johnsbr1** [comment]
Thanks for the explanation!
